apiVersion: v1
kind: Service
metadata:
  name: nginxdemo-service
  namespace: devopsgroup
spec:
  type: NodePort
  selector:
    app: nginxdemo-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000 
